client_config_backend: settings
client_config:
  client_id: 184248815846-6ndj5qonqgvg9ham1h28a71sqioj7sd3.apps.googleusercontent.com
  client_secret: Gfd5baklFDSJXjH_qMJQZRJV

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
